version : 2.1
jobs:
  build:
    working_directory: ~/protectors
    docker:
      - image: openjdk:19 
    steps:
      - checkout
      - run: ~/Protectors/src/atm_fingerprint/ && javac ATMMain.java && java ATMMain
  test: 
    working_directory: ~/Protectors
    docker:
      - image: openjdk:19
    steps:
      - checkout
      - run: ~/Protectors/src/atm_fingerprint/ && javac ATMMain.java && java ATMMain


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
