version : 2.1
jobs:
  build:
    working_directory: ~/Protectors
    docker:
      - image: "cimg/openjdk:17.0"
    steps:
      - checkout
      - run: cd src/atm_fingerprint/ && javac ATMMain.java && java ATMMain
  test: 
    working_directory: ~/Protectors
    docker:
      - image: "cimg/openjdk:17.0"
    steps:
      - checkout
      - run: cd src/atm_fingerprint/ && javac ATMMain.java && java ATMMain


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
