version : 2.1
jobs:
  build-and-compile-java:
    working_directory: ~/Protectors
    docker:
      - image: "circleci/Protectors"
    steps:
      - checkout
      - run: Protectors\src\atm_fingerprint\ && javac Login.java && java Login
  test: 
    working_directory: ~/Protectors
    docker:
      - image: "circleci/Protectors"
    steps:
      - checkout
      - run: Protectors\src\atm_fingerprint\ && javac Login.java && java Login


workflows:
  backendCompiling:
    jobs:
      - build-and-compile-java
