version : 2.1
jobs:
  build:
    working_directory: ~/Protectors
    docker:

      - image: "cimg/openjdk:19.0"

    steps:
      - checkout
      - run: cd src/atm_fingerprint/ && java -cp ".:../resources/*" ATMMain.java
  test:
    working_directory: ~/Protectors
    docker:
      - image: "cimg/openjdk:19.0"
    steps:
      - checkout
      - run: cd src  && javac -cp ".:resources/*" atm_fingerprint/ATMMain.java && javac -cp ".:resources/*" ../tests/tests.java && java -cp ".:../tests:resources/*" ../tests/TestRunner.java



workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
