/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import javax.swing.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NS
 */
public class Login extends JFrame {

    /**
     * Creates new form ATMmain
     */
    String appTitle = "Fingerprint Authentication";
    String key = "";

    Connection conn;

    boolean fingerprintAuthenticated = false;

    String filePath = "";

    Thread trd;

    private JPanel Authentication;
    private JLabel Heading;
    private JPanel Signup;
    private JButton addFingerprint;
    private JButton backBtnAuth;
    private JButton createAcccountBtn;
    private JPanel fingerPrintCheckPanel;
    private JLabel hiddenField;
    private JPanel home;
    private JLabel jLabel10;
    private JLabel jLabel11;
    private JLabel jLabel12;
    private JLabel jLabel13;
    private JLabel jLabel14;
    private JLabel jLabel15;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JScrollPane jScrollPane1;
    private JSeparator jSeparator1;
    private JTable lastTransactionTable;
    private JPanel lastTransactions;
    private JTextField loginName;
    private JButton logoutBtn;
    private JLayeredPane mainPanel;
    private JPanel moneyTransferPanel;
    private JButton navToHome;
    private JButton navToHome1;
    private JButton navToHome2;
    private JLabel navToLogin;
    private JLabel navToSignup;
    private JLabel navToSignup1;
    private JLabel navToSignup2;
    private JButton nextBtn;
    private JTextField transferAccountName;
    private JTextField transferAmount;
    private JButton transferBtn;
    private JButton transferConformedBtn;
    private JTextField userNameSignup;
    private JButton viewBalanceBtn;
    private JButton viewTransactionBtn;
    private JLabel welcomeText;
    private JPanel withDrawalPanel;
    private JTextField withdrawAmount;
    private JButton withdrawConformedBtn;
    private JButton withdrawalBtn;
    // End of variables declaration//GEN-END:variables

    public Login() throws ClassNotFoundException, SQLException {
        initComponents();
        filePath = System.getProperty("user.dir");
        filePath += "\\AnsiTemplate.ansi";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Heading = new JLabel();
        mainPanel = new JLayeredPane();
        Authentication = new JPanel();
        loginName = new JTextField();
        jLabel2 = new JLabel();
        nextBtn = new JButton();
        jLabel3 = new JLabel();
        navToSignup = new JLabel();
        Signup = new JPanel();
        userNameSignup = new JTextField();
        addFingerprint = new JButton();
        jLabel5 = new JLabel();
        createAcccountBtn = new JButton();
        jLabel6 = new JLabel();
        navToLogin = new JLabel();
        home = new JPanel();
        welcomeText = new JLabel();
        jLabel4 = new JLabel();
        withdrawalBtn = new JButton();
        viewBalanceBtn = new JButton();
        viewTransactionBtn = new JButton();
        transferBtn = new JButton();
        logoutBtn = new JButton();
        withDrawalPanel = new JPanel();
        withdrawAmount = new JTextField();
        navToHome = new JButton();
        jLabel7 = new JLabel();
        withdrawConformedBtn = new JButton();
        jLabel8 = new JLabel();
        navToSignup1 = new JLabel();
        moneyTransferPanel = new JPanel();
        transferAccountName = new JTextField();
        navToHome1 = new JButton();
        jLabel9 = new JLabel();
        transferConformedBtn = new JButton();
        jLabel10 = new JLabel();
        navToSignup2 = new JLabel();
        jLabel11 = new JLabel();
        transferAmount = new JTextField();
        lastTransactions = new JPanel();
        navToHome2 = new JButton();
        jLabel12 = new JLabel();
        jScrollPane1 = new JScrollPane();
        lastTransactionTable = new JTable();
        fingerPrintCheckPanel = new JPanel();
        jLabel13 = new JLabel();
        jLabel15 = new JLabel();
        jLabel14 = new JLabel();
        backBtnAuth = new JButton();
        jSeparator1 = new JSeparator();
        hiddenField = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        Heading.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Heading.setHorizontalAlignment(SwingConstants.CENTER);
        Heading.setText("Fingerprint Authentication - ATM");

        mainPanel.setLayout(new java.awt.CardLayout());

        loginName.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        loginName.setHorizontalAlignment(JTextField.CENTER);
        loginName.setToolTipText("Username");
        loginName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                //loginNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Login");

        nextBtn.setBackground(new java.awt.Color(0, 204, 0));
        nextBtn.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        nextBtn.setText("Next >");
        nextBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                // nextBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(143, 143, 152));
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setLabelFor(home);
        jLabel3.setText("Enter your username");
        jLabel3.setToolTipText("");

        navToSignup.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        navToSignup.setForeground(new java.awt.Color(77, 77, 223));
        navToSignup.setHorizontalAlignment(SwingConstants.CENTER);
        navToSignup.setLabelFor(home);
        navToSignup.setText("Click here to create a new account");
        navToSignup.setToolTipText("");
        navToSignup.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        navToSignup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                // navToSignupMouseClicked(evt);
            }
        });

        GroupLayout AuthenticationLayout = new GroupLayout(Authentication);
        Authentication.setLayout(AuthenticationLayout);
        AuthenticationLayout.setHorizontalGroup(
                AuthenticationLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(AuthenticationLayout.createSequentialGroup()
                                .addContainerGap(386, Short.MAX_VALUE)
                                .addGroup(AuthenticationLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addGroup(GroupLayout.Alignment.TRAILING, AuthenticationLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                .addComponent(loginName, GroupLayout.PREFERRED_SIZE, 308, GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel3)
                                                .addGroup(AuthenticationLayout.createSequentialGroup()
                                                        .addGap(48, 48, 48)
                                                        .addGroup(AuthenticationLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                                                .addGroup(GroupLayout.Alignment.TRAILING, AuthenticationLayout.createSequentialGroup()
                                                                        .addComponent(jLabel2)
                                                                        .addGap(487, 487, 487))
                                                                .addGroup(GroupLayout.Alignment.TRAILING, AuthenticationLayout.createSequentialGroup()
                                                                        .addComponent(navToSignup)
                                                                        .addGap(400, 400, 400)))))
                                        .addGroup(GroupLayout.Alignment.TRAILING, AuthenticationLayout.createSequentialGroup()
                                                .addComponent(nextBtn, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
                                                .addGap(438, 438, 438))))
        );
        AuthenticationLayout.setVerticalGroup(
                AuthenticationLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(AuthenticationLayout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2)
                                .addGap(92, 92, 92)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(loginName, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(nextBtn, GroupLayout.PREFERRED_SIZE, 38, GroupLayout.PREFERRED_SIZE)
                                .addGap(80, 80, 80)
                                .addComponent(navToSignup, GroupLayout.PREFERRED_SIZE, 45, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(39, Short.MAX_VALUE))
        );


        mainPanel.add(Authentication, "card2");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jSeparator1)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(mainPanel)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(hiddenField)
                                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Heading, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                        .addComponent(Heading, GroupLayout.PREFERRED_SIZE, 51, GroupLayout.PREFERRED_SIZE)
                                        .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(hiddenField, GroupLayout.PREFERRED_SIZE, 0, GroupLayout.PREFERRED_SIZE)
                                                .addGap(16, 16, 16)))
                                .addGap(18, 18, 18)
                                .addComponent(jSeparator1, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(mainPanel, GroupLayout.PREFERRED_SIZE, 489, GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );


        pack();
    }

   /* private boolean navToPanel(JPanel jpanel) {

        this.mainPanel.removeAll();
        this.mainPanel.add(jpanel);
        this.mainPanel.repaint();
        this.mainPanel.revalidate();

        return true;
    }

          private void navToSignupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_navToSignupMouseClicked
           // TODO add your handling code here:
                 navToPanel(this.Signup);
            }//GEN-LAST:event_navToSignupMouseClicked*/
        public static void main (String args[]){
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
             */
            try {
                for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            } catch (UnsupportedLookAndFeelException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    try {
                        new Login().setVisible(true);
                    } catch (ClassNotFoundException ex) {

                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (SQLException ex) {
                        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            });
        }
    }


